interceptor.go, interceptor_test.go
Currently a bug where propagation only occurs in client interceptors. 
This fixes that and propagates in both server and client interceptors
=> Fix header propagation

attributes.go, interceptor_test.go, option.go
This removes all references to `net.peer.ip` addresses and replaces it with `net.peer.name` as is required for the opentelemetry specification. 
> net.peer.name | string | RPC server host name. [3] | example.com | Required
> -- | -- | -- | -- | --
> Additional attribute requirements: At least one of the following sets of attributes is required:
> [net.sock.peer.addr](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/span-general.md)
[net.peer.name](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/span-general.md)
Also notably this can also be set to up addresses:
> When host component is an IP address, instrumentations SHOULD NOT do a reverse proxy lookup to …
=> Change net.peer.ip to net.peer.name, lower cardinality option

interceptor.go, interceptor_test.go
- Only set SpanStatus when errors are non nil
- Leave SpanStatus unset for all non error scenarios
- Add test for Streaming 
- Update old tests to check SpanStatus
Fixes: https://github.com/bufbuild/connect-opentelemetry-go/issues/51
=> Fix span status

README.md, bench_test.go, interceptor.go, interceptor_test.go, option.go, otelconnect.go
The only use case we have of using this package is using a number of Interceptors instead of just the `WithTelemetry` option. It's anticipated that if a project is using connect-opentelemetry-go the chances are that it's probably also using other interceptors. In that case it makes sense to expose a `New` function that returns an `type interceptor struct` that can be plugged into the existing interceptor plumming. 
The only difference this makes to existing projects that are using `WithTelemetry` is that they now need to use `connect.WithInterceptor(otelconnect.New())`
Fixes: https://github.com/bufbuild/connect-opentelemetry-go/issues/21
=> Remove WithTelemetry option in favor of connect.WithInterceptors(otelconnect.NewInterceptor())

interceptor_test.go
Adds a test to make sure that propagation of baggage works correctly 
Related: https://github.com/bufbuild/connect-opentelemetry-go/issues/55
=> Add baggage propagation test

attributes.go, interceptor.go, interceptor_test.go, otelconnect.go, streaming.go
Conforms to https://github.com/open-telemetry/opentelemetry-specification/pull/3116 
Namely:
- `buf_connect` is not `connect_rpc` 
- `status_code` is now `error_code` for `connect_rpc` instances. This means that no attribute is set for success
- introduce string consts for grpc, grpcweb connect_rpc...
=> Semconv conformance to connect specification

attributes.go, instruments.go, interceptor.go, interceptor_test.go, option.go, otelconnect.go
Adds metadata attributes to all types. 
Metadata attributes are _only_ defined in the spec for trace span attributes.
The ones defined are:
- `rpc.<protocol>.request.metadata.<normalised key>`
- `rpc.<protocol>.response.metadata.<normalised key>`
Where; 
- The `<normalised key>` are specified via the `WithTraceMetadataAttributes(requestKeys, responseKeys []string)` Option. 
- protocol is one of `grpc`, `grpc_web` or `buf_connect` 
- "normalised"  is `<key> being the normalized gRPC Metadata key (lowercase, with - characters replaced by _), the value being the metadata values.` as per the [spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/rpc.md#grpc-request-and-response-metadata). This is implemented …
=> Add metadata attributes

.github/workflows/ci.yaml, go.mod, go.sum
connect-go v1.5.2 requires go 1.19, this updates both
=> Update to go v1.19 + connect-go v1.5.2

README.md
I am about to release `v0.1.0` of this repo, so this removes references to `untagged alpha release`
=> Remove reference to `untagged alpha release` for preparation of v0.1.0

README.md
Add ecosystem part in README.md
=> Add ecosystem part in README.md

README.md
Amend the README to include common gotchas (WithTrustRemote and
cardinality), and add a link to the docs on connect.build.
Addresses the comments on #91.
=> Include FAQs in the README

README.md
[This commit](https://github.com/bufbuild/connect-opentelemetry-go/pull/111) to main depends on the stable go opentelemetry api, and since opentelemetry-go is stable we should update the docs and release a stable version of connect-opentelemetry-go
=> Change references from alpha to stable

Makefile, attributes.go
A "not modified" error really should _not_ be counted as an error with "Unknown" error code. So this addresses that.
That does beg the question: how _should_ it be handled? I see three options:
1. Skip the status code attribute entirely, since "not modified" doesn't cleanly map to an RPC code.
2. Treat it as "okay"/zero, since it's not really an error condition.
3. Don't use an RPC status code and instead use an HTTP status code attribute.
This PR currently uses the last option. But I'm happy to change it, based on what a larger group of minds thinks is the best way to label this state.
=> Handle "not modified" errors properly

interceptor.go, option.go, otelconnect.go
Addresses https://github.com/bufbuild/connect-opentelemetry-go/issues/92 with a new interceptor option to omit the sent/received events.
=> add new option to omit adding RPC events in unary interceptor

.golangci.yml, README.md, attributes.go, bench_test.go, interceptor.go, interceptor_test.go, otelconnect.go, payloadinterceptor.go, pingserver_test.go
Add `connect` and `pingv1` import aliases for packages whose name doesn't match.
similar https://github.com/bufbuild/knit-go/pull/22
=> Add import aliases for packages whose name doesn't match

interceptor.go, interceptor_test.go, option.go, otelconnect.go, streaming.go
- Changes name of option from `OmitRPCEvents` to `OmitTraceEvents` to be more clear
- Omits trace events for streaming too
- Adds tests
Closes: #92
=> Make option to omit trace events apply to streaming RPCs

README.md
This updates links to point to the new conformance repo (fka crosstests).
Note - not intended to merge until the conformance repo is moved.
=> Update refs for conformance repo

bench_test.go
Simplifies the benchmarking to 4 cases, baseline and with interceptors for both unary and streaming cases. Switched to `RunParallel` to measure overhead per RPC request rather than grouped by the concurrency setting. Reduced streaming to a single round trip to better compare against unary flows:
```
pkg: connectrpc.com/otelconnect
BenchmarkStreamingBase-8                   19152             58334 ns/op          534279 B/op        204 allocs/op
BenchmarkStreamingWithInterceptor-8        19467             62326 ns/op          546378 B/op        302 allocs/op
BenchmarkUnaryBase-8                       41461             27704 ns/op           14514 B/op        156 allocs/op
BenchmarkUnaryWithInterceptor-8            37642             30383 ns/op           25723 B/op        241 allocs/op
PASS …
```
=> Use RunParallel for benchmarks

instruments.go, interceptor_test.go
When otelconnect and otelgrpc are used in the same project, the Prometheus exporter fails because the descriptions of the metrics produced by the two libraries differ. See #154 for details.
This PR copies over the metrics descriptions used in the `otelgrpc` instrumentation to metrics produced by `otelconnect`.
Fixes #154
=> Add descriptions to metrics to match otelgrpc

interceptor_test.go
Fixes the missing description in a test causing CI failures. Due to a merge issue. See CI failures here: https://github.com/connectrpc/otelconnect-go/actions/runs/7117347326
=> Fix merge conflict on descriptions

interceptor.go, interceptor_test.go
This pull request fixes https://github.com/connectrpc/otelconnect-go/issues/122
refs:
- https://github.com/open-telemetry/opentelemetry-specification/pull/3333
- https://github.com/open-telemetry/opentelemetry-go-contrib/pull/3685
=> Align gRPC server status code to span status code

attributes.go, interceptor.go, interceptor_test.go, option.go, otelconnect.go, streaming.go
Context in client streams doesn't include the span due to the `*Request` requiring information only included once the connection is created. This PR proposes removing the `*Request` in favour of simply providing the `connect.Spec` information. Now we can correctly initialize the span creation before passing the context to the client handler.
- Removes exported `*Request` object (breaking change)
- Changes option filters to use `connect.Spec` instead of `*Request` (breaking change)
=> Remove *Request to fix streaming client context

.golangci.yml, context.go, context_legacy.go, interceptor.go, payloadinterceptor.go
CloseRequest and CloseResponse must both be called before the span can be ended. Remove onCloseCalled bool as it's easy to derive.
On `CloseResponse` we must have stopped the connection and it is now safe to close the span. To handle context cancellation and ensure the span is always closed [`context.AfterFunc`](https://pkg.go.dev/context#AfterFunc) is added with a simpler backport for !go1.21.
=> Close ClientStreaming on context cancellation

.github/workflows/ci.yaml, .golangci.yml, Makefile, go.mod, interceptor.go, interceptor_test.go
Increases min version to v1.20 and current v1.22. Also included is a lint bump with associated fixes.
=> Bump Go to v1.22

README.md
OTel moved these documentation pages to a new repo.
https://github.com/open-telemetry/oteps/blob/main/text/0227-separate-semantic-conventions.md
=> fix: update otel rpc conventions link in readme

interceptor.go, interceptor_test.go
Fix a data race for a streaming client on close when a the context is cancelled. This was introduced in #152 where we changed the behaviour to trigger a close on context cancellation. The state must be locked to avoid a data race with Send/Receive calls.
Closes #170, #171.
=> Fix data race on streaming client close

MAINTAINERS.md
This proposes adding myself [emcfarlane](https://github.com/emcfarlane) as a maintainer, per [Connect's governance policy](https://connectrpc.com/docs/governance/project-governance).
CC @akshayjshah , @jhump.
=> Add emcfarlane as maintainer

README.md, doc.go
Noticed that the links in doc.go weren't updated in #163, so tracked down what the best links for those documents are — also fixed up some links in the README.
=> Fixup links

.golangci.yml, LICENSE, Makefile, attributes.go, attributes_test.go, bench_test.go, instruments.go, interceptor.go, interceptor_test.go, internal/gen/observability/ping/v1/ping.pb.go, internal/gen/observability/ping/v1/pingv1connect/ping.connect.go, internal/proto/observability/ping/v1/ping.proto, option.go, otelconnect.go, payloadinterceptor.go, pingserver_test.go, streaming.go
Remove unnecessary allocations by pre-sizing slice allocations, reducing slice allocations in helper methods, and removing unused variables along the happy path (no errors).
Additionally switch to using `clear` to reset filtered out part of attribute slices since we're on Go 1.22, update license headers, and update golangci-lint.
=> Reduce unnecessary allocations in interceptors

.github/workflows/ci.yaml, .golangci.yml, Makefile, go.mod, interceptor.go, interceptor_test.go
Update the interceptor to bypass some calls if the span is non-recording. Update buf and golangci-lint to the latest version.
=> Avoid some calls if span is non recording

interceptor.go, interceptor_test.go, option.go, otelconnect.go
WithTraceParentResponseHeader enables injecting the traceparent header into response headers for server-side interceptors. This allows clients to correlate their requests with server-side traces.
=> Add WithPropagateResponseHeader option

MAINTAINERS.md
Philip is a maintainer of Connect-Kotlin, very strong in Go, has made contributions to this repo for performance improvements, and is very familiar with OpenTelemetry including the Go runtime library for it. I propose that he be added as an official maintainer here.
=> Add Philip Warren as a maintainer

.github/workflows/ci.yaml
This way, we can mark "ci (go:latest)" and "ci (go:previous)" as required checks and never have to change them again. Without an explicit name, it defaults to the job key ("ci") plus the properties of the matrix. So this was using names like "ci (latest, v1.25.x)", which still has the Go version in it, which we don't want.
=> Fix ci job names to only include the go-version name, not version number
